Feature/continious integration
LuxoftSDL/sdl_core_ci pull request #1
Opened 2020-09-09 16:31 UTC by LuxoftAKutsan

2020-09-10 14:59 UTC, YarikMamykin requested changes
Generally excellent work!

2020-09-10 14:59 UTC, YarikMamykin commented on README.md
> + - [Alexander Kutsan](https://github.com/LuxoftAKutsan) : YMamykin@luxoft.com
Please swap emails

2020-09-10 14:59 UTC, YarikMamykin commented on README.md
> +In case of special requiest (not ordinaary builds for special feature, restart certain jobs, etc, ...) please contact any of following persons:
Please fix typos `requiest` and `ordinaary`

2020-09-11 14:11 UTC, YarikMamykin commented on README.md
> +In case of special requiest (not ordinaary builds for special feature, restart certain jobs, etc, ...) please contact any of following persons:
@YarikMamykin done in https://github.com/LuxoftSDL/sdl_core_ci/pull/1/commits/a280e8231a579ed768b23a5aa05ba0f1c1e3b2e6

2020-09-11 14:11 UTC, YarikMamykin commented on README.md
> + - [Alexander Kutsan](https://github.com/LuxoftAKutsan) : YMamykin@luxoft.com
@YarikMamykin done in https://github.com/LuxoftSDL/sdl_core_ci/pull/1/commits/a280e8231a579ed768b23a5aa05ba0f1c1e3b2e6

2020-09-11 14:11 UTC, YarikMamykin approved these changes

2020-09-11 14:51 UTC, dboltovskyi requested changes

2020-09-11 14:51 UTC, dboltovskyi commented on README.md
> + - [Code style check](https://opensdl-jenkins.prjdmz.luxoft.com/view/all/job/Develop_SDL_Checkstyle/) : Use [check_style.sh](https://github.com/smartdevicelink/sdl_core/blob/master/tools/infrastructu
Typo `compilence`

2020-09-11 14:51 UTC, dboltovskyi commented on README.md
> +Required input values for feeature job:
Typo `feeature`

2020-09-11 14:51 UTC, dboltovskyi commented on README.md
> + - Feture name (will be used for view title)
Typo `Feture`

2020-09-11 14:51 UTC, dboltovskyi commented on README.md
> + - sdl_atf_test_scripts deature branch and repository. (master by default)
Typo `deature`

2020-09-11 14:51 UTC, dboltovskyi commented on README.md
> + - Additional info : evoluiton proposal, links to issues, etc ...
Typo `evoluiton`

2020-09-11 14:51 UTC, dboltovskyi commented on README.md
> + - Regression tests
All bullet points should start with upper (or lower) case

2020-09-11 14:51 UTC, dboltovskyi commented on README.md
> + - Smoke automates tests
Typo `automates`

2020-09-11 14:51 UTC, dboltovskyi commented on README.md
> + - Regression tests
Regression automated tests?

2020-09-11 14:51 UTC, dboltovskyi commented on README.md
> +Job artifacts contains build results, ATF reports, SDL logs,  etc ...
Typo `contain`

2020-09-11 14:51 UTC, dboltovskyi commented on README.md
> +   - [![bage][develop http ut bage]][develop http ut]
All policy flows I would name as:
 - `PROPRIETARY`
 - `EXTERNAL_PROPRIETARY`
 - `HTTP`

Everywhere in doc

2020-09-11 14:51 UTC, dboltovskyi commented on README.md
> +Develop branch push and nightly automated scripts checks available in [view](https://opensdl-jenkins.prjdmz.luxoft.com/view/all/) :
Provided link is for `all` jobs, not for `develop`

2020-09-11 14:51 UTC, dboltovskyi commented on README.md
> +
Let's put a link to https://opensdl-jenkins.prjdmz.luxoft.com/view/Jenkins_Utils/ and some description for all three jobs

2020-09-11 14:51 UTC, dboltovskyi commented on README.md
> +[check style bage]: https://img.shields.io/jenkins/build?jobUrl=https%3A%2F%2Fopensdl-jenkins.prjdmz.luxoft.com%2Fview%2Fall%2Fjob%2FDevelop_SDL_Checkstyle%2F&label=check%20style
Is this correct link?

2020-09-11 14:51 UTC, dboltovskyi commented on README.md
> +[unit test coverage]: https://opensdl-jenkins.prjdmz.luxoft.com/view/all/job/develop_weekly_coverage/
Link is broken

2020-09-11 18:19 UTC, dboltovskyi requested changes

2020-09-11 18:19 UTC, dboltovskyi commented on README.md
> +When feature is delivered and no checks for it needed appropriate jobs on CI can be deleted with [Feature job delete](https://opensdl-jenkins.prjdmz.luxoft.com/view/Jenkins_Utils/job/Jenkins_Utils_De
`... no checks for it is needed ...`

2020-09-11 18:19 UTC, dboltovskyi commented on README.md
> +https://img.shields.io/jenkins/build?jobUrl=https%3A%2F%2Fopensdl-jenkins.prjdmz.luxoft.com%2Fview%2Fall%2Fjob%2FDevelop_SDL_NoUT_E%2F&label=external%20PROPRIETARY%20build%20%20no%20UT
`label=external`,  here and everywhere needs to be corrected
also `label=http%20unit` and others

2020-09-11 18:19 UTC, dboltovskyi commented on README.md
>  #### Automated RC regression
Do we need to add some links here?

2020-09-11 18:19 UTC, dboltovskyi commented on README.md
> +[unit test coverage]: https://opensdl-jenkins.prjdmz.luxoft.com/view/Develop_weekly/job/Develop_SDL_Checkstyle/
Is this correct job for UT coverage?

2020-09-11 20:40 UTC, dboltovskyi approved these changes

2020-09-14 02:20 UTC, merged