Move scripts to scm
LuxoftSDL/sdl_core_ci pull request #3
Opened 2021-01-28 19:59 UTC by yarpryvalikhin

Util scripts were moved under version control to support and maintain jobs

2021-02-01 22:12 UTC, dboltovskyi requested changes

2021-02-01 22:12 UTC, dboltovskyi commented on scripts/utils_rename.groovy
> +  trgView.doAddJobToView("${item.name}")
Original script didn't add jobs into view.
Jobs will be added into view automatically since RegExp is defined in original View.

Having RegExp approach we would have more flexible view. Sometimes new jobs are cloned from existing ones. And they would be added automatically.

2021-02-01 22:12 UTC, dboltovskyi commented on scripts/utils_clone.groovy
> +  trgView.doAddJobToView("${job.name}")
Original script didn't add jobs into view.
Please see comment for the `rename` script

2021-02-01 22:12 UTC, dboltovskyi commented on scripts/utils_clone.groovy
> +    }
I don't think code in lines `71` - `77` will work.
This part of code originally is required to set job's parameter like `SDL_REPOSITORY`, `SDL_BRANCH` etc. to a new defined values.
However in a current implementation values for all these parameters are not updated. Just source values are copied.
The reason of that is line `72` where `jobParams` variable is created, but not used within `xml` object.

To verify just run `http://172.26.147.12/view/Jenkins_Utils/job/Jenkins_Utils_Clone-clone` with non-default values and check configuration for a new created `*RUN*` jobs.

2021-02-02 13:53 UTC, yarpryvalikhin commented on scripts/utils_clone.groovy
> +  trgView.doAddJobToView("${job.name}")
without these lines view will be empty but jobs will be created

2021-08-12 14:52 UTC, dboltovskyi commented
All the development moved to https://github.com/LuxoftSDL/sdl_core_ci/pull/6

2021-08-12 14:52 UTC, closed without merging