Update dockerfiles
LuxoftSDL/sdl_core_ci pull request #4
Opened 2021-03-15 21:15 UTC by yarpryvalikhin

Dockerfile were added and updated to support Ubuntu 18.04

2021-03-25 13:20 UTC, dboltovskyi commented
Currently we have the following list of actual docker images:
```
  1. SDL:
    - label: linux_build      => docker_image: sdl_build.u18.04
    - label: linux_coverage   => docker_image: sdl_build.u18.04.cppcheck    
    - label: cppcheck         => docker_image: cppcheck_ubuntu18:latest
    - label: linux_build_u20  => docker_image: sdl_build.u20.04
  2. ATF:
    - label: atf_runner       => docker_image: remote_atf:u18_runner
    - label: remote_atf       => docker_image: remote_atf:u18
    - label: atf_runner_u20   => docker_image: sdl_build.u20.04
  3. Git sync
    - label: git              => docker_image: git:1
```
Please add missing ones

2021-03-25 13:22 UTC, dboltovskyi commented
Can we combine `sdl_build.u18.04` and `remote_atf:u18_runner` (and also `remote_atf:u18`)
E.g. for Ubuntu 20 we have single image for all purposes: `sdl_build.u20.04`

2021-03-25 13:23 UTC, dboltovskyi requested changes

2021-03-25 13:23 UTC, dboltovskyi commented on dockerfiles/Dockerfile.sdl_build.u18.04
> +CMD ["/usr/sbin/sshd", "-D"]
I guess we need to add new line here and to other files where it missing

2021-03-25 13:23 UTC, dboltovskyi commented on dockerfiles/Dockerfile.cppcheck.u18.04
> +FROM ubuntu:18.04
I guess it's better to rename dockerfile to `sdl_build.u18.04.cppcheck`

2021-04-06 18:50 UTC, yarpryvalikhin commented on dockerfiles/Dockerfile.sdl_build.u18.04
> +CMD ["/usr/sbin/sshd", "-D"]
New line was added

2021-04-06 18:50 UTC, yarpryvalikhin commented on dockerfiles/Dockerfile.cppcheck.u18.04
> +FROM ubuntu:18.04
Renamed

2021-04-10 10:05 UTC, dboltovskyi requested changes

2021-04-10 10:05 UTC, dboltovskyi commented on dockerfiles/Dockerfile.sdl_build.u18.04
> +CMD ["/entrypoint.sh"]
When I run a container for this image 
```
docker run --rm -it c046fe18a3df
```
I got the following message:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/entrypoint.sh": permission denied: unknown.
```

However on Jenkins through `ssh` it works fine

2021-04-10 10:05 UTC, dboltovskyi commented on dockerfiles/Dockerfile.sdl_build.u18.04
> +        lua-lpeg-dev \
Package `lua5.2` is missing. `ATF` can't be built without it. See details: http://172.26.147.12/view/Dockerfiles/job/Dockerfiles_u18_ATF_BUILD_RUNNER/1/console

2021-04-10 10:05 UTC, dboltovskyi commented on dockerfiles/Dockerfile.sdl_build.u18.04.cppcheck
> +#    sudo echo "jenkins ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
Are these lines commented intentionally? `sshd` is required to start container within Jenkins.
I was not able to start this container and got error:
```
Note: Disabled 4 min 37 sec ago due to error. Will re-enable in 22 sec.
Reason: Template provisioning failed.

java.io.IOException: SSH service hadn't started after 20 seconds.	at io.jenkins.docker.connector.DockerComputerSSHConnector.createLauncher(DockerComputerSSHConnector.java:256)
```

2021-04-10 10:05 UTC, dboltovskyi commented on dockerfiles/Dockerfile.sdl_build.u18.04.cppcheck
> +#    lcov genhtml html2text bc xmlstarlet xsltproc dos2unix
Don't we need all these packages?

2021-04-10 10:05 UTC, dboltovskyi commented on dockerfiles/Dockerfile.sdl_build.u18.04.cppcheck
> +CMD ["/usr/sbin/sshd", "-D"]
Does an image created within this Dockerfile allow to run `linux_coverage` as well as `cppcheck` jobs?

2021-04-29 01:43 UTC, dboltovskyi commented on dockerfiles/Dockerfile.sdl_build.u18.04.cppcheck
> +CMD ["/usr/sbin/sshd", "-D"]
Looks like no. Please find details: http://172.26.147.12/view/Dockerfiles/job/Dockerfiles_u18_SDL_Coverage/

2021-04-29 02:05 UTC, dboltovskyi requested changes

2021-04-29 02:05 UTC, dboltovskyi commented on dockerfiles/entrypoint.sh
> +#!/bin/bash
Why do we need this entrypoint?
E.g. for Dockerfile.sdl_build.u20.04 it is not required

2021-04-29 02:05 UTC, dboltovskyi commented on dockerfiles/entrypoint.sh
> +sudo LD_LIBRARY_PATH="/home/developer/sdl/3rd_party/lib:/home/developer/sdl/3rd_party/x86_64/lib:." -u developer "./RemoteTestingAdapterServer"
Starting of `RemoteTestingAdapterServer` is implemented in https://raw.githubusercontent.com/LuxoftSDL/sdl_core_ci/impl/atf_remote_upd/scripts/atf_runner_remote.sh which is used in test jobs for remote connection:
 - Dockerfiles_u18_ATF_Smoke_TCP_Remote_P
 - Dockerfiles_u20_ATF_Smoke_TCP_Remote_P

2021-05-20 02:04 UTC, dboltovskyi requested changes

2021-05-20 02:04 UTC, dboltovskyi commented on dockerfiles/Dockerfile.sdl_build.u18.04
> +RUN apt-get update && apt-get -q -y install cmake libssl-dev libusb-1.0-0-dev \
@yarpryvalikhin Please notice within image created from this version of Dockerfile it's impossible to build ATF.
Details in http://172.26.147.12/view/Dockerfiles/job/Dockerfiles_u18_ATF_BUILD_RUNNER/5/console
The reason of that is absence of `cmake-3.11` which was removed in latest commit https://github.com/LuxoftSDL/sdl_core_ci/pull/4/commits/9d7f261193bb5428dee02d27db43619cf4a91fac

2021-05-20 02:04 UTC, dboltovskyi commented on dockerfiles/Dockerfile.sdl_build.u18.04.cppcheck
> +
New line is missing at the end of the file.

2021-05-26 15:53 UTC, dboltovskyi approved these changes
@yarpryvalikhin Thank you for updates

2021-06-02 12:53 UTC, merged